### PR TITLE
initial stab at take

### PR DESCRIPTION
**Pull request by ianzapolsky**
not ready for a merge, but i'd like us to use this as a jumping off point to think about use cases/problems surrounding theoretically infinite list generators. (RE #24)

### CODE REVIEW

**Comment by ianzapolsky** [comment]
while we had originally discussed using tuples as parameter/return value for a generator, this introduces a lot of overhead complication. 

firstly, you cannot access an element of a tuple of unknown size with a variable. For example, this will not compile:
```
for (int i = 0; i < std::tuple_size<decltype(mytuple)>::value; i++)
    std::cout << std::get<i>(mytuple) << std::endl;
```
secondly, because our collections class requires that all elements be of the same type, the parameters being passed to our generator function should also always be of the same type. So a vector would work just fine, and now a user can define a sequence that relies on an arbitrary number of parameters of the same type passed into the generator via a vector.

**Comment by natebrennand** [comment]
This seems like we should implement a different class for streams and then implement `take` on that.

**Comment by ianzapolsky** [comment]
going to delete this branch, because from the sound of it we are going to go a different direction with this and define a different Stream class. Does this sound correct?

**Comment by natebrennand** [comment]
sgtm, I'll work on the stream implementation later this week.

**Pull request closed without merging**
